export const dinner =[
{id: 1,
name: "Salmon with Grapefruit and Lentil Salad",
"shortDescription": "How we dream about our future",
price: 9.99,
details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
photo: "https://iili.io/2CI592.png",
category: "dinner",
inCart: false,
count: 0,
total: 0
},
{id: 2,
name: "Lemony Salmon Piccata",
shortDescription: "How we dream about our future",
price: 10.99,
details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
photo: "https://iili.io/2CI7uS.md.png",
category: "dinner",
inCart: false,
count: 0,
total: 0
},
{id: 3,
name: "Park Tenderloin With Quiona Pilaf",
shortDescription: "How we dream about our future",
price: 12.99,
details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
photo: "https://iili.io/2CIYw7.png",
category: "dinner",
inCart: false,
count: 0,
total: 0
},
{id: 4,name: "French Fries with cheese",
shortDescription: "How we dream about our future",
price: 8.99,
details: "At Bamboo Inn, we offer Free prawn crackers with food order over £18. FREE mini vegetable spring rolls with food order over night.",
photo: "https://iili.io/2CIat9.png",
category: "dinner",
inCart: false,
count: 0,
total: 0
},
{id: 5,
name: "Gralic Butter Baked Salmon",
shortDescription: "How we dream about our future",
price: 6.99,
details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
photo: "https://iili.io/2CIua4.png",
category: "dinner",
inCart: false,
count: 0,
total: 0
},
{id: 6,
name: "Baked Chicken",
shortDescription: "How we dream about our future",
price: 9.99,
details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
photo: "https://iili.io/2CIA8l.png",
category: "dinner",
inCart: false,
count: 0,
total: 0
},
]
